// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlEaXVP9KnsD_e160--uvlHVBUF6dDIXA',
    appId: '1:455550634183:web:744ee9162da826c39716e2',
    messagingSenderId: '455550634183',
    projectId: 'authentication-e0e7b',
    authDomain: 'authentication-e0e7b.firebaseapp.com',
    storageBucket: 'authentication-e0e7b.firebasestorage.app',
    measurementId: 'G-T2ZY63GJ1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdIYC6x6SPir-sP2-yBcL6CIemLRLVPzo',
    appId: '1:455550634183:android:e5c360cf459833719716e2',
    messagingSenderId: '455550634183',
    projectId: 'authentication-e0e7b',
    storageBucket: 'authentication-e0e7b.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlEaXVP9KnsD_e160--uvlHVBUF6dDIXA',
    appId: '1:455550634183:web:73a747f4f50a111b9716e2',
    messagingSenderId: '455550634183',
    projectId: 'authentication-e0e7b',
    authDomain: 'authentication-e0e7b.firebaseapp.com',
    storageBucket: 'authentication-e0e7b.firebasestorage.app',
    measurementId: 'G-Y5LW9TRHJC',
  );
}
